using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SEDC.PizzaApp.Domain.Models
{
    public class Pizza
    {
        [Key] //Primary Key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //the values will be generated by the db, following identity principle
        public int Id { get; set; }   
        public string Name { get; set; }   
        public bool IsOnPromotion { get; set; }
        //PizzaOrder is on the M side in the relation
        public List<PizzaOrder> PizzaOrders { get; set; }
    }
}
